### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#266]
![Screenshot_20231231_151728](https://github.com/trovu/trovu/assets/1151915/55d78ead-400a-4464-938c-8f4d8835ca53)
The screen layout has too many stuff  around the only interesting input field. 

I suggest to make an Url parameter &tinyscreen or &easy or so which suppresses unneeded texts.

**Comment by georgjaehnig** [comment]
I agree that it currently looks cluttered and needs a cleanup.

I am reluctant about extra new URL parameters, as one needs to document them, and also keep them forever, otherwise you get in the way of users using them.

If you want a quick solution for now (until the redesign), I suggest these browser extensions:

- [Nuke Anything Enhanced](https://addons.mozilla.org/en-US/firefox/addon/nuke-anything-enhanced/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
- [Nukem](https://chromewebstore.google.com/detail/nukem/kpogandfndblomniegfaeakkjchmiedi?hl=en-GB)

**Comment by georgjaehnig** [comment]
Current idea: The current intro text ("Search 1000+ websites …") and the hint below the input ("Select with ⬆️ ⬇️ for …") should both become a box each, that can be dismissed / removed with a click on a ✖️ in its corner. 

(The setting will be saved in a cookie, the first click on ✖️ will trigger a dialog where the user can confirm cookie storage.) 

All boxes shall be placed above the input, next to each other *horizontally*, overflowing to the right, outside the screen. So instead of dismissing them, one can also scroll horizontally to read them all.

The warning messages ("Could not match shortcut", "Shortcuts have been reloaded") shall be also part of these boxes, always enqueued at the beginning.

cc @stefanschramm
