### ISSUE TITLE
Quick correction for shortcut 'dpl 1'

### ISSUE THREAD

**Issue by pja-gomes** [trovu/trovu#474]
Hello,
Please fix the url of "dpl 1" in line 2012 on `data/shortcuts/o.yml`.
The current url has a dot character after hash symbol, instead of a language abbreviation (eg. en, it etc.). This obstructs translating text on the fly with the 'dpl' shortcut. 

NOW: 
`url: https://www.deepl.com/translator#./<$language>/<text>`

POSSIBLE EDIT:
`url: https://www.deepl.com/translator#en/<$language>/<text>`

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #474</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @pja-gomes</code> (replace <code>20</code> with the amount, and <code>@pja-gomes</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by georgjaehnig** [comment]
Thanks for your PR.

The original link used to work, and was equivalent to selecting "Detect language". Seems it stopped working now.

Your possible edit would not autodetect anymore. In fact, for users with `language=en`, it would send them to
```
https://www.deepl.com/translator#en/en/<text>
```

So ideally, we find a way again to build a link that will autodetect the source language. I've already tried these, but none of them did the trick :(
```
https://www.deepl.com/translator#auto/en/strom
https://www.deepl.com/translator#/en/strom
https://www.deepl.com/translator#*/en/strom
```
Maybe you are more creative?

Otherwise, I'd drop that generic shortcut in `o`, and create one with the target language as argument, e.g.
```
https://www.deepl.com/translator#<$language>/<target-language>/<text>
```

**Comment by pja-gomes** [comment]
Hello,
I too didn't have much luck with "autodetect" url, that is why I was
suggesting defaulting to "#en" but your proposed solution is much more elegant
i.e. replacing that shortcut with something such as :
https://www.deepl.com/translator#<$language>/<target-language>/<text>

Kind regards,
pg.

**Comment by georgjaehnig** [comment]
Sorry for the delay. Now added the new `dpl 2` as requested: 7160b8f50464ea042ea3063a0d1f386641d43414

Still need to find sth reasonable for `dpl 1`. 🤔
